app:
  env: 'dev'
  port: 80
  signalr_port: 81
database:
  driver: 'mysql'
  host: '192.168.201.2'
  port: 3306
  database: 'database_test'
  username: 'superuser'
  password: 'NbARrZtv7ZhvWq'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'
jwt:
  secret: 'sdfsdfsrty45634kkhtrghtdgdfss345t678fs'
  issuer: 'sw'
  audience: 'sw'
  expire_minutes: 43200
  clock_skew_minutes: 1440
eos:
  region: 'beijing2'
  endpoint: 'http://test.cn'
  buket_name: 'algorithm'
  access_id: ''
  access_secret: ''

